int _putchar(char c);
void rev_string(char *s);
void puts2(char *str);
void _puts(char *str);
void reset_to_98(int *n);
void swap_int(int *a, int *b);
int _strlen(char *s);
void print_rev(char *s);
char *_strcat(char *dest, char *src);
char *_strncpy(char *dest,char *src,int n);
int _strcmp(char *s1, char *s2);
